"""add goal column to weekly_plan

Revision ID: a5ac723d2b68
Revises: 64a7374172eb
Create Date: 2025-11-12 12:06:42.824372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5ac723d2b68'
down_revision: Union[str, Sequence[str], None] = '64a7374172eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weekly_plans', sa.Column('goal', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weekly_plans', 'goal')
    # ### end Alembic commands ###
