"""initial schema

Revision ID: bfc6a157e51d
Revises: 
Create Date: 2025-10-31 09:28:56.501497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfc6a157e51d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_templates',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('diet_type', sa.Text(), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('meals_for_day', sa.JSON(), nullable=False),
    sa.Column('prep_time_min', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('goal', 'diet_type', 'day_index', name='uq_meal_goal_diet_day')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=False),
    sa.Column('last_name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('workout_templates',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('day_type', sa.Text(), nullable=False),
    sa.Column('focus', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('coach_note', sa.Text(), nullable=False),
    sa.Column('equipment', sa.JSON(), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('goal', 'day_type', name='uq_workout_goal_day')
    )
    op.create_table('user_profile',
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.Text(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('activity_level', sa.Text(), nullable=True),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('diet_type', sa.Text(), nullable=True),
    sa.Column('fav_protein', sa.Text(), nullable=True),
    sa.Column('experience_level', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('weekly_plans',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('daily_targets', sa.JSON(), nullable=False),
    sa.Column('week_meals', sa.JSON(), nullable=False),
    sa.Column('week_workouts', sa.JSON(), nullable=False),
    sa.Column('grocery_list', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'week_start_date', name='uq_user_week')
    )
    op.create_index(op.f('ix_weekly_plans_user_id'), 'weekly_plans', ['user_id'], unique=False)
    op.create_index(op.f('ix_weekly_plans_week_start_date'), 'weekly_plans', ['week_start_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekly_plans_week_start_date'), table_name='weekly_plans')
    op.drop_index(op.f('ix_weekly_plans_user_id'), table_name='weekly_plans')
    op.drop_table('weekly_plans')
    op.drop_table('user_profile')
    op.drop_table('workout_templates')
    op.drop_table('users')
    op.drop_table('meal_templates')
    # ### end Alembic commands ###
