"""add fitness program tables

Revision ID: faa5e2e590a4
Revises: bfc6a157e51d
Create Date: 2025-11-05 13:22:11.995411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faa5e2e590a4'
down_revision: Union[str, Sequence[str], None] = 'bfc6a157e51d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cooldown_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('program_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('goal', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('days_per_week', sa.Integer(), nullable=False),
    sa.Column('duration_weeks', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('rest_day_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('warmup_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('program_day_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('focus', sa.String(), nullable=True),
    sa.Column('warmup_block_id', sa.Integer(), nullable=True),
    sa.Column('cooldown_block_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cooldown_block_id'], ['cooldown_block.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['program_template.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warmup_block_id'], ['warmup_block.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id', 'day_number', name='uq_program_daynum')
    )
    op.create_table('program_week_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=True),
    sa.Column('is_rest', sa.Boolean(), nullable=False),
    sa.Column('rest_slug', sa.String(), nullable=True),
    sa.CheckConstraint('weekday BETWEEN 1 AND 7', name='ck_weekday_1_7'),
    sa.ForeignKeyConstraint(['program_id'], ['program_template.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('program_id', 'weekday', name='uq_program_weekday')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('program_week_template')
    op.drop_table('program_day_template')
    op.drop_table('warmup_block')
    op.drop_table('rest_day_template')
    op.drop_table('program_template')
    op.drop_table('cooldown_block')
    # ### end Alembic commands ###
